package eu.vitamo.app.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class AppPalette(
    val primary: Color,
    val primaryHover: Color,
    val primaryActive: Color,
    val primarySoft: Color,
    val primaryBg: Color,
    val onPrimary: Color,
    val secondary: Color,
    val secondaryHover: Color,
    val secondaryActive: Color,
    val secondaryBg: Color,
    val onSecondary: Color,
    val pageBg: Color,
    val surface: Color,
    val surface2: Color,
    val surface3: Color,
    val onSurface: Color,
    val overlay: Color,
    val backdrop: Color,
    val border: Color,
    val borderStrong: Color,
    val divider: Color,
    val text: Color,
    val textMuted: Color,
    val textSubtle: Color,
    val textInverse: Color,
    val link: Color,
    val linkHover: Color,
    val success: Color,
    val successHover: Color,
    val successBg: Color,
    val onSuccess: Color,
    val warning: Color,
    val warningHover: Color,
    val warningBg: Color,
    val onWarning: Color,
    val error: Color,
    val errorHover: Color,
    val errorBg: Color,
    val onError: Color,
    val info: Color,
    val infoHover: Color,
    val infoBg: Color,
    val onInfo: Color,
    val focusRing: Color,
    val focusOutline: Color,
    val inputBg: Color,
    val inputBorder: Color,
    val inputBorderHover: Color,
    val inputBorderFocus: Color,
    val inputPlaceholder: Color,
    val inputDisabledBg: Color,
    val inputDisabledText: Color,
    val buttonBg: Color,
    val buttonBgHover: Color,
    val buttonBgActive: Color,
    val buttonText: Color,
    val buttonSecondaryBg: Color,
    val buttonSecondaryBorder: Color,
    val buttonSecondaryText: Color,
    val buttonSecondaryHoverBg: Color,
)

internal val LightPalette = AppPalette(
    primary = Color(0xFF16A34A),
    primaryHover = Color(0xFF15803D),
    primaryActive = Color(0xFF166534),
    primarySoft = Color(0xFF22C55E),
    primaryBg = Color(0xFFECFDF5),
    onPrimary = Color(0xFFFFFFFF),
    secondary = Color(0xFF0EA5E9),
    secondaryHover = Color(0xFF0284C7),
    secondaryActive = Color(0xFF0369A1),
    secondaryBg = Color(0xFFE0F2FE),
    onSecondary = Color(0xFFFFFFFF),
    pageBg = Color(0xFFFFFFFF),
    surface = Color(0xFFFFFFFF),
    surface2 = Color(0xFFF8FAFC),
    surface3 = Color(0xFFF1F5F9),
    onSurface = Color(0xFF0F172A),
    overlay = Color(0x80111A2A),
    backdrop = Color(0x59111A2A),
    border = Color(0xFFE5E7EB),
    borderStrong = Color(0xFFCBD5E1),
    divider = Color(0x14111A2A),
    text = Color(0xFF0F172A),
    textMuted = Color(0xFF6B7280),
    textSubtle = Color(0xFF94A3B8),
    textInverse = Color(0xFFFFFFFF),
    link = Color(0xFF0EA5E9),
    linkHover = Color(0xFF0284C7),
    success = Color(0xFF16A34A),
    successHover = Color(0xFF15803D),
    successBg = Color(0xFFECFDF5),
    onSuccess = Color(0xFFFFFFFF),
    warning = Color(0xFFF59E0B),
    warningHover = Color(0xFFD97706),
    warningBg = Color(0x0DF59E0B),
    onWarning = Color(0xFF111827),
    error = Color(0xFFEF4444),
    errorHover = Color(0xFFDC2626),
    errorBg = Color(0xFFFEF2F2),
    onError = Color(0xFFFFFFFF),
    info = Color(0xFF0EA5E9),
    infoHover = Color(0xFF0284C7),
    infoBg = Color(0xFFE0F2FE),
    onInfo = Color(0xFF0F172A),
    focusRing = Color(0x590EA5E9),
    focusOutline = Color(0xFF0EA5E9),
    inputBg = Color(0xFFFFFFFF),
    inputBorder = Color(0xFFE5E7EB),
    inputBorderHover = Color(0xFFCBD5E1),
    inputBorderFocus = Color(0xFF0EA5E9),
    inputPlaceholder = Color(0xFF94A3B8),
    inputDisabledBg = Color(0xFFF1F5F9),
    inputDisabledText = Color(0xFF94A3B8),
    buttonBg = Color(0xFF16A34A),
    buttonBgHover = Color(0xFF15803D),
    buttonBgActive = Color(0xFF166534),
    buttonText = Color(0xFFFFFFFF),
    buttonSecondaryBg = Color(0xFFFFFFFF),
    buttonSecondaryBorder = Color(0xFFE5E7EB),
    buttonSecondaryText = Color(0xFF0F172A),
    buttonSecondaryHoverBg = Color(0xFFF8FAFC),
)

internal val DarkPalette = AppPalette(
    primary = Color(0xFF22C55E),
    primaryHover = Color(0xFF16A34A),
    primaryActive = Color(0xFF15803D),
    primarySoft = Color(0xFF4ADE80),
    primaryBg = Color(0xFF052E16),
    onPrimary = Color(0xFF03130A),
    secondary = Color(0xFF38BDF8),
    secondaryHover = Color(0xFF0EA5E9),
    secondaryActive = Color(0xFF0284C7),
    secondaryBg = Color(0xFF082F49),
    onSecondary = Color(0xFF031019),
    pageBg = Color(0xFF0B1220),
    surface = Color(0xFF111827),
    surface2 = Color(0xFF1F2937),
    surface3 = Color(0xFF334155),
    onSurface = Color(0xFFE2E8F0),
    overlay = Color(0xB30F172A),
    backdrop = Color(0x800F172A),
    border = Color(0xFF334155),
    borderStrong = Color(0xFF475569),
    divider = Color(0x52CBD5E1),
    text = Color(0xFFE2E8F0),
    textMuted = Color(0xFF94A3B8),
    textSubtle = Color(0xFF64748B),
    textInverse = Color(0xFF0F172A),
    link = Color(0xFF38BDF8),
    linkHover = Color(0xFF7DD3FC),
    success = Color(0xFF22C55E),
    successHover = Color(0xFF16A34A),
    successBg = Color(0xFF052E16),
    onSuccess = Color(0xFFEFFEF5),
    warning = Color(0xFFFBBF24),
    warningHover = Color(0xFFF59E0B),
    warningBg = Color(0x331D1403),
    onWarning = Color(0xFFFFF7E6),
    error = Color(0xFFF87171),
    errorHover = Color(0xFFEF4444),
    errorBg = Color(0xFF450A0A),
    onError = Color(0xFFFFEDEE),
    info = Color(0xFF38BDF8),
    infoHover = Color(0xFF0EA5E9),
    infoBg = Color(0xFF082F49),
    onInfo = Color(0xFFE0F2FE),
    focusRing = Color(0x6638BDF8),
    focusOutline = Color(0xFF38BDF8),
    inputBg = Color(0xFF0F172A),
    inputBorder = Color(0xFF334155),
    inputBorderHover = Color(0xFF475569),
    inputBorderFocus = Color(0xFF38BDF8),
    inputPlaceholder = Color(0xFF64748B),
    inputDisabledBg = Color(0xFF1E293B),
    inputDisabledText = Color(0xFF64748B),
    buttonBg = Color(0xFF22C55E),
    buttonBgHover = Color(0xFF16A34A),
    buttonBgActive = Color(0xFF15803D),
    buttonText = Color(0xFF03130A),
    buttonSecondaryBg = Color(0xFF111827),
    buttonSecondaryBorder = Color(0xFF334155),
    buttonSecondaryText = Color(0xFFE2E8F0),
    buttonSecondaryHoverBg = Color(0xFF1F2937),
)

internal val LocalAppPalette = staticCompositionLocalOf { LightPalette }

internal fun appMaterialColorScheme(darkTheme: Boolean): ColorScheme {
    val palette = if (darkTheme) DarkPalette else LightPalette
    return if (darkTheme) {
        darkColorScheme(
            primary = palette.primary,
            onPrimary = palette.onPrimary,
            secondary = palette.secondary,
            onSecondary = palette.onSecondary,
            background = palette.pageBg,
            onBackground = palette.text,
            surface = palette.surface,
            onSurface = palette.onSurface,
            surfaceVariant = palette.surface2,
            onSurfaceVariant = palette.textMuted,
            outline = palette.border,
            error = palette.error,
            onError = palette.onError,
            errorContainer = palette.errorBg,
            onErrorContainer = palette.onError,
        )
    } else {
        lightColorScheme(
            primary = palette.primary,
            onPrimary = palette.onPrimary,
            secondary = palette.secondary,
            onSecondary = palette.onSecondary,
            background = palette.pageBg,
            onBackground = palette.text,
            surface = palette.surface,
            onSurface = palette.onSurface,
            surfaceVariant = palette.surface2,
            onSurfaceVariant = palette.textMuted,
            outline = palette.border,
            error = palette.error,
            onError = palette.onError,
            errorContainer = palette.errorBg,
            onErrorContainer = palette.onError,
        )
    }
}

object VitaTheme {
    val palette: AppPalette
        @Composable get() = LocalAppPalette.current
}

