package eu.vitamo.app.api.contracts.auth

object AuthErrorCode {
    const val INVALID_EMAIL_CODE = "INVALID_EMAIL"
    const val INVALID_PASSWORD_RESET_CODE = "INVALID_PASSWORD_RESET_CODE"
    const val INVALID_CREDENTIALS_CODE = "INVALID_CREDENTIALS"
    const val EMAIL_NOT_VERIFIED_CODE = "EMAIL_NOT_VERIFIED"
    const val EMAIL_ALREADY_EXISTS_CODE = "EMAIL_ALREADY_EXISTS"
    const val VERIFICATION_ATTEMPTS_EXCEEDED_CODE = "VERIFICATION_ATTEMPTS_EXCEEDED"
    const val EMAIL_VERIFICATION_FAILED_CODE = "EMAIL_VERIFICATION_EMAIL_FAILED"
    const val FORGOT_PASSWORD_FAILED_CODE = "FORGOT_PASSWORD_FAILED_CODE"
    const val INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE"

    const val EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    const val INVALID_EMAIL = "INVALID_EMAIL"
}