CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- Users
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    alias VARCHAR(100),
    bio VARCHAR(500),
    birth_date DATE,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    profile_image_id UUID,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    email_verified_at TIMESTAMPTZ,
    deleted_at BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_uidx
    ON users (email);

CREATE INDEX IF NOT EXISTS users_display_name_idx
    ON users (display_name);

CREATE INDEX IF NOT EXISTS idx_users_profile_image_id
    ON users (profile_image_id);

-- -----------------------------------------------------------------------------
-- Devices
--
-- devices.id is the persistent clientInstanceId generated by the client.
-- Device/client metadata lives here instead of being copied to every refresh token.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    client_type VARCHAR(20) NOT NULL,
    client_name VARCHAR(100) NOT NULL,
    client_version VARCHAR(100),
    platform VARCHAR(20) NOT NULL,
    os_version VARCHAR(100),
    device_name VARCHAR(255),
    device_model VARCHAR(255),
    firebase_installation_id TEXT,
    last_seen_at_epoch_seconds BIGINT,
    created_at_epoch_seconds BIGINT NOT NULL,
    updated_at_epoch_seconds BIGINT NOT NULL,
    deleted_at_epoch_seconds BIGINT
);

CREATE INDEX IF NOT EXISTS devices_user_id_idx
    ON devices (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS devices_firebase_installation_id_uidx
    ON devices (firebase_installation_id)
    WHERE firebase_installation_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- Refresh tokens
--
-- A refresh token now points to a Device. Client/device metadata is no longer
-- duplicated on the token itself.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGSERIAL PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id UUID NOT NULL REFERENCES devices (id) ON DELETE CASCADE,
    expired_at_epoch_seconds BIGINT NOT NULL,
    last_used_at_epoch_seconds BIGINT,
    revoked_at_epoch_seconds BIGINT,
    replaced_by_session_id UUID,
    created_at_epoch_seconds BIGINT NOT NULL,
    updated_at_epoch_seconds BIGINT NOT NULL,
    deleted_at_epoch_seconds BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS refresh_tokens_token_hash_uidx
    ON refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS refresh_tokens_user_id_idx
    ON refresh_tokens (user_id);

CREATE INDEX IF NOT EXISTS refresh_tokens_device_id_idx
    ON refresh_tokens (device_id);

CREATE INDEX IF NOT EXISTS refresh_tokens_expired_at_idx
    ON refresh_tokens (expired_at_epoch_seconds);

CREATE INDEX IF NOT EXISTS refresh_tokens_revoked_at_idx
    ON refresh_tokens (revoked_at_epoch_seconds);

-- -----------------------------------------------------------------------------
-- Email verification
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS email_verification_challenges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    attempts INT NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS email_verification_challenges_user_id_idx
    ON email_verification_challenges (user_id);

CREATE INDEX IF NOT EXISTS email_verification_challenges_email_idx
    ON email_verification_challenges (email);

CREATE INDEX IF NOT EXISTS email_verification_challenges_purpose_idx
    ON email_verification_challenges (purpose);

CREATE INDEX IF NOT EXISTS email_verification_challenges_expires_at_idx
    ON email_verification_challenges (expires_at);

CREATE INDEX IF NOT EXISTS email_verification_challenges_consumed_at_idx
    ON email_verification_challenges (consumed_at);

-- -----------------------------------------------------------------------------
-- Password reset
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP NULL,
    attempts INT NOT NULL DEFAULT 3,
    last_attempt_at TIMESTAMP NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_password_reset_tokens_token_hash
    ON password_reset_tokens (token_hash);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id
    ON password_reset_tokens (user_id);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at
    ON password_reset_tokens (expires_at);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_consumed_at
    ON password_reset_tokens (consumed_at);

-- -----------------------------------------------------------------------------
-- Media assets
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS media_assets (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    purpose VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    visibility VARCHAR(32) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    mime_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    width INTEGER,
    height INTEGER,
    sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    CONSTRAINT fk_media_assets_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT uq_media_assets_storage_key
        UNIQUE (storage_key),

    CONSTRAINT chk_media_assets_type
        CHECK (media_type IN ('IMAGE', 'VIDEO')),

    CONSTRAINT chk_media_assets_status
        CHECK (status IN ('PENDING', 'READY', 'FAILED', 'DELETED')),

    CONSTRAINT chk_media_assets_visibility
        CHECK (visibility IN (
            'PUBLIC',
            'AUTHENTICATED',
            'FRIENDS',
            'PRIVATE'
        )),

    CONSTRAINT chk_media_assets_size
        CHECK (size_bytes >= 0)
);

CREATE INDEX IF NOT EXISTS idx_media_assets_owner_id
    ON media_assets (owner_id);

CREATE INDEX IF NOT EXISTS idx_media_assets_status
    ON media_assets (status);

CREATE INDEX IF NOT EXISTS idx_media_assets_owner_status
    ON media_assets (owner_id, status);

-- -----------------------------------------------------------------------------
-- Friendships
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS friendships (
    id UUID PRIMARY KEY,
    user_low_id UUID NOT NULL,
    user_high_id UUID NOT NULL,
    requested_by_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,

    CONSTRAINT fk_friendships_user_low
        FOREIGN KEY (user_low_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_friendships_user_high
        FOREIGN KEY (user_high_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_friendships_requested_by
        FOREIGN KEY (requested_by_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_friendships_different_users
        CHECK (user_low_id <> user_high_id),

    CONSTRAINT chk_friendships_requester_is_participant
        CHECK (
            requested_by_id = user_low_id
            OR requested_by_id = user_high_id
        ),

    CONSTRAINT chk_friendships_status
        CHECK (status IN ('PENDING', 'ACCEPTED')),

    CONSTRAINT uq_friendships_user_pair
        UNIQUE (user_low_id, user_high_id)
);

CREATE INDEX IF NOT EXISTS idx_friendships_user_low
    ON friendships (user_low_id);

CREATE INDEX IF NOT EXISTS idx_friendships_user_high
    ON friendships (user_high_id);

CREATE INDEX IF NOT EXISTS idx_friendships_requested_by
    ON friendships (requested_by_id);

CREATE INDEX IF NOT EXISTS idx_friendships_status
    ON friendships (status);