package eu.vitamo.app.network

/**
 * Auto-generated by scripts/update-compose-dev-network-config.sh
 * Do not edit manually for local development.
 */
object DevNetworkConfig {
    const val API_BASE_URL: String = "http://192.168.178.93:8080/api"
}
