package eu.vitamo.app.network

/**
 * Auto-generated by scripts/update-compose-dev-network-config.sh
 *
 * Do not edit manually for local development.
 */
object DevNetworkConfig {

    /**
     * LAN-adres van de development machine.
     *
     * Werkt voor fysieke apparaten op hetzelfde netwerk
     * en kan ook vanuit de Android Emulator worden gebruikt.
     */
    const val API_BASE_URL: String = "http://192.168.178.93:8080/api"

    /**
     * Speciale host waarmee een Android Emulator
     * rechtstreeks de host-machine kan bereiken.
     */
    const val ANDROID_EMULATOR_API_BASE_URL: String =
        "http://10.0.2.2:8080/api"
}
