#!/bin/bash
set -e

cd "$(dirname "$0")/.."

echo "🔎 Lokaal IP-adres ophalen voor Compose-app..."

# ------------------------------------------------------------
# Local network IP ophalen
# ------------------------------------------------------------

LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || true)

if [ -z "$LOCAL_IP" ]; then
  LOCAL_IP=$(ipconfig getifaddr en1 2>/dev/null || true)
fi

if [ -z "$LOCAL_IP" ]; then
  LOCAL_IP=$(ifconfig | awk '
    /inet / &&
    $2 != "127.0.0.1" &&
    $2 !~ /^169\.254\./
    {
      print $2
      exit
    }
  ')
fi

if [ -z "$LOCAL_IP" ]; then
  echo "❌ Kon geen lokaal IP-adres vinden."
  exit 1
fi

SERVER_PORT="8080"

# Deze URL werkt voor:
# - fysieke Android devices op hetzelfde netwerk
# - Android Emulator
# - iOS devices/simulator zolang de Mac bereikbaar is
API_BASE_URL="http://$LOCAL_IP:$SERVER_PORT/api"

# Speciale Android Emulator host.
# Wordt toegevoegd aan network_security_config zodat deze ook
# gebruikt kan worden wanneer nodig.
ANDROID_EMULATOR_HOST="10.0.2.2"

echo ""
echo "✅ Netwerkconfiguratie:"
echo "   Mac IP:              $LOCAL_IP"
echo "   API base URL:        $API_BASE_URL"
echo "   Android emulator:    http://$ANDROID_EMULATOR_HOST:$SERVER_PORT/api"
echo ""

# ------------------------------------------------------------
# 1. Update Kotlin dev config
# ------------------------------------------------------------

KOTLIN_CONFIG_FILE="app/shared/src/commonMain/kotlin/eu/vitamo/app/network/DevNetworkConfig.kt"

mkdir -p "$(dirname "$KOTLIN_CONFIG_FILE")"

cat > "$KOTLIN_CONFIG_FILE" <<EOF
package eu.vitamo.app.network

/**
 * Auto-generated by scripts/update-compose-dev-network-config.sh
 *
 * Do not edit manually for local development.
 */
object DevNetworkConfig {

    /**
     * LAN-adres van de development machine.
     *
     * Werkt voor fysieke apparaten op hetzelfde netwerk
     * en kan ook vanuit de Android Emulator worden gebruikt.
     */
    const val API_BASE_URL: String = "$API_BASE_URL"

    /**
     * Speciale host waarmee een Android Emulator
     * rechtstreeks de host-machine kan bereiken.
     */
    const val ANDROID_EMULATOR_API_BASE_URL: String =
        "http://$ANDROID_EMULATOR_HOST:$SERVER_PORT/api"
}
EOF

echo "✅ DevNetworkConfig bijgewerkt:"
echo "   $KOTLIN_CONFIG_FILE"
echo ""

# ------------------------------------------------------------
# 2. Update Android network security config
# ------------------------------------------------------------

NETWORK_SECURITY_FILE="app/androidApp/src/main/res/xml/network_security_config.xml"

if [ ! -f "$NETWORK_SECURITY_FILE" ]; then
  echo "❌ Network security config niet gevonden:"
  echo "   $NETWORK_SECURITY_FILE"
  exit 1
fi

python3 - <<PY
from pathlib import Path

file_path = Path("$NETWORK_SECURITY_FILE")

local_ip = "$LOCAL_IP"
android_emulator_host = "$ANDROID_EMULATOR_HOST"

content = file_path.read_text()

start = "<!-- AUTO-GENERATED-DEV-IP-START -->"
end = "<!-- AUTO-GENERATED-DEV-IP-END -->"

if start not in content or end not in content:
    raise SystemExit(
        "❌ Markers niet gevonden in network_security_config.xml. "
        "Voeg AUTO-GENERATED-DEV-IP-START en "
        "AUTO-GENERATED-DEV-IP-END toe."
    )

replacement = f"""{start}
        <!-- Fysieke Android devices / lokaal netwerk -->
        <domain includeSubdomains="true">{local_ip}</domain>

        <!-- Android Emulator -> host machine -->
        <domain includeSubdomains="true">{android_emulator_host}</domain>
        {end}"""

before = content.split(start, 1)[0]
after = content.split(end, 1)[1]

new_content = before + replacement + after

file_path.write_text(new_content)
PY

echo "✅ Network security config bijgewerkt:"
echo "   $NETWORK_SECURITY_FILE"
echo ""
echo "   Cleartext HTTP toegestaan voor:"
echo "   - $LOCAL_IP"
echo "   - $ANDROID_EMULATOR_HOST"
echo ""

# ------------------------------------------------------------
# Resultaat
# ------------------------------------------------------------

echo "🚀 Development netwerkconfiguratie gereed."
echo ""
echo "Fysieke Android telefoon:"
echo "   $API_BASE_URL"
echo ""
echo "Android Emulator:"
echo "   $API_BASE_URL"
echo ""
echo "Alternatief voor Android Emulator:"
echo "   http://$ANDROID_EMULATOR_HOST:$SERVER_PORT/api"
echo ""
echo "⚠️ Zorg ervoor dat:"
echo "   - telefoon en Mac op hetzelfde netwerk zitten"
echo "   - server luistert op 0.0.0.0:$SERVER_PORT"
echo "   - macOS firewall verbindingen naar de server toestaat"